import type { ClientPayment } from '@/types/payment';

export const demoPayments: ClientPayment[] = [
  {
    id: 'pay-001',
    clientId: 'client-ivan',
    clientName: 'Иван',
    whatsapp: '+7 777 111 22 33',
    instagram: '@ivan_bench',
    tariff: 'full_online_month',
    tariffName: 'Полное онлайн ведение',
    amount: 40000,
    currency: 'KZT',
    paid: true,
    paymentDate: '2026-06-01',
    startDate: '2026-06-03',
    endDate: '2026-07-03',
    source: 'kaspi',
    notes: 'Оплатил полный месяц, нужна программа на жим и плечи.',
  },
  {
    id: 'pay-002',
    clientId: 'client-askar',
    clientName: 'Аскар',
    whatsapp: '+7 701 555 44 33',
    instagram: '@askar_power',
    tariff: 'plan_month',
    tariffName: 'План на месяц',
    amount: 6000,
    currency: 'KZT',
    paid: true,
    paymentDate: '2026-05-24',
    startDate: '2026-05-24',
    endDate: '2026-06-07',
    source: 'kaspi',
    notes: 'Нужно продлить после окончания.',
  },
  {
    id: 'pay-003',
    clientId: 'client-marat',
    clientName: 'Марат',
    whatsapp: '+7 747 222 10 10',
    tariff: 'free_lesson',
    tariffName: 'Бесплатное занятие',
    amount: 0,
    currency: 'KZT',
    paid: true,
    paymentDate: '2026-05-20',
    startDate: '2026-05-20',
    endDate: '2026-05-27',
    source: 'other',
    notes: 'Бесплатное занятие проведено, надо закрывать на оплату.',
  },
  {
    id: 'pay-004',
    clientId: 'client-dana',
    clientName: 'Дана',
    whatsapp: '+7 707 909 00 11',
    instagram: '@dana_fit',
    tariff: 'full_online_month',
    tariffName: 'Полное онлайн ведение',
    amount: 40000,
    currency: 'KZT',
    paid: true,
    paymentDate: '2026-05-29',
    startDate: '2026-05-29',
    endDate: '2026-06-29',
    pauseUntil: '2026-06-10',
    source: 'bank_transfer',
    notes: 'Пауза из-за командировки.',
  },
  {
    id: 'pay-005',
    clientId: 'client-serik',
    clientName: 'Серик',
    whatsapp: '+7 705 333 99 88',
    tariff: 'plan_month',
    tariffName: 'План на месяц',
    amount: 6000,
    currency: 'KZT',
    paid: false,
    paymentDate: null,
    startDate: '2026-06-03',
    endDate: '2026-06-17',
    source: 'kaspi',
    notes: 'План готовить только после оплаты.',
  },
];
